[package]
name = "leancop"
version = "0.1.0"
authors = ["Michael Färber <michael.faerber@gedenkt.at>"]
edition = "2018"

[dependencies]
cop = { path = "../cop" }

clap = "3.0.0-beta.2"
colosseum = "0.2"
env_logger = "0.7"
hashbrown = "0.9"
log = "0.4"
tptp = "0.28"
